// client/angular2/NvslOnlineAngular2App/src/app/news/edit-news/edit-news.component.ts
import { Component, OnInit } from '@angular/core';
import { NgForm } from '@angular/forms';
import { Router, ActivatedRoute } from '@angular/router';
import { Subscription }       from 'rxjs/Subscription';

import { INews } from '../../shared/interfaces/interfaces';
import { News } from '../../shared/models/news';

import { DataService } from '../../shared/services/data.service';

@Component({
  selector: 'app-edit-news',
  templateUrl: './edit-news.component.html',
  styleUrls: ['./edit-news.component.css']
})
export class EditNewsComponent implements OnInit {

    public pageTitle: string = 'Edit News';  
    public singleNews = new News(0, '', '', false, '');
    public inews: INews;
    private errorMessage: string;
    private sub: Subscription; 

    constructor(private dataService: DataService,
                private router: Router,
                private route: ActivatedRoute) { }

    ngOnInit() {
        this.sub = this.route.params.subscribe(
              params => {
                  let id = +params['id'];
                  this.getNews(id);
          });
    }

    getNews(id: number) {
        this.dataService.getSingleNews(id).subscribe(
            news => this.inews = news,
            error => this.errorMessage = <any>error,
            () => this.setValues(this.inews));
    }

    setValues(news: INews) {
        this.singleNews = news;
    }

    submitForm(form: NgForm) {
        this.dataService.updateSingleNews(this.singleNews)
            .subscribe(
                data => console.log('success: ', data),
                err => console.log('error: ', err),
                () => this.router.navigate(['/news'])
            );
    }    

    onBack(): void {
        this.router.navigate(['/news']);
    }

}

<div class="main-form main-center">
<h3>{{pageTitle}}</h3>

<form #form="ngForm" (submit)="submitForm(form)" novalidate>    
    <!-- NAME -->
    <div class="form-group" [class.has-error]="name.invalid && !name.pristine" >
        <label for="title" class="control-label">Name</label>
        <input type="text" #name="ngModel" name="name" [(ngModel)]="singleNews.title" class="form-control" placeholder="Title" required />
        <p *ngIf="name.invalid && !name.pristine" class="help-block">Title is required.</p>           
    </div>

    <!-- DESCRIPTION -->
    <div class="form-group" [class.has-error]="description.invalid && !description.pristine" >
        <label for="title" class="control-label">Description</label>
        <textarea #description="ngModel" name="description" [(ngModel)]="singleNews.description" class="form-control" rows="10" placeholder="Description" required></textarea>
        <p *ngIf="description.invalid && !description.pristine" class="help-block">Description is required.</p>           
    </div>
    
    <!-- SUBMIT BUTTON -->
    <div class="form-group">    
        <input type="submit" class="btn btn-primary" [disabled]="form.invalid" value="Update" /> 
        <a class='btn btn-primary' (click)='onBack()' style='width:80px'>
            Back
        </a>   
    </div>
</form>
</div>
<!--singleNews {{singleNews|json}}
<br>
Angular {{form.value | json}}
<br>
for  is valid {{form.valid}}-->

// client/react/nvslonlineapp/src/components/News/editNews.js
import React from 'react';
import { Link, Route, Router, Redirect } from "react-router-dom";
import SideBar from '../SideBar.js';
import './News.css';
import api from '../../api/api.js';

export default class editNews extends React.Component {

    constructor(props) 
    {
        super(props);    
        
        this.state = {
          SingleNews: [],
          pageTitle: 'Edit News',
          title: '',
          description: '',
          redirect: false,
          //created: ''
        }

        let NewsId = props.match.params.id;

        api.getSinglenNews(NewsId).then((response) => {
            console.log(response);
            this.setState({
			        SingleNews: response,
              title: response.title,
              description: response.description
		        })
        });

        
        this.HandleSave = this.HandleSave.bind(this);
        this.handleChange = this.handleChange.bind(this);

        
    }

    HandleSave(e) {
        e.preventDefault();

        if (!this.showFormErrors()) {      
            console.log('form is invalid: do not submit');
        } 
        else {
            console.log('form is valid !!!!!!!');
            
            let OnlyNews = {
              'id': this.props.match.params.id,
              'title': this.state.title,
              'description': this.state.description,
              'modified': new Date()
            }

            api.updateSingleNews(OnlyNews)
              .then((response) => {
                  console.log('success');    
                  this.setState({ redirect: true });                
              })
              .catch((error) => {
                  console.log('error');
            });  
        }
         
    }

    handleChange(e) {

      e.target.classList.add('active');
      
      this.setState({
        [e.target.name]: e.target.value,               
      });

      this.showInputError(e.target.name);

    }

    showFormErrors() {

        const inputs = document.querySelectorAll('input');
        let isFormValid = true;
        
        inputs.forEach(input => {

          input.classList.add('active');
                      
          const  isInputValid = this.showInputError(input.name);      
          
          if (!isInputValid) {
            isFormValid = false;
          }
        });

        const textarea = document.querySelector('textarea');

        const IsAreaTextValid = this.showInputError(textarea.name);

        if (!IsAreaTextValid) {
          isFormValid = false;
        }
            
        return isFormValid;
    }  

    showInputError(refName) {
        
        if (refName)
        {      
          const validity = this.refs[refName].validity;
          const label = document.getElementById(`${refName}Label`).textContent;
          const error = document.getElementById(`${refName}Error`);
          
          if ( !validity.valid ) {
              if( validity.valueMissing ) {  
                  document.getElementById(`${refName}Label`).style = "color: red";             
                  error.textContent = `${label} is a required field`; 
                  this.refs[refName].style = "border: 1px solid red;";
              }        
              return false;
          }     
          else {
                document.getElementById(`${refName}Label`).style = "color: #2c3e50"; 
                error.textContent = '';
                this.refs[refName].style = "border: 1px solid #dce4ec;";             
          } 
        }

        return true;
    }

    render() {
    return (
      <div>
          <div className="container-fluid">
          <div className="col-md-2 sidebar">
            <SideBar />
          </div>
          <div className="col-md-10">
            <div className="main-form main-center">
              <h3>{this.state.pageTitle}</h3>

              {this.state.redirect ? <Redirect to="/news" />:
                 <form noValidate> 

                    {/*NAME*/}
                    <div className="form-group" >
                        <label id="titleLabel" className="control-label">Title</label>
                        <input className="form-control"
                            type="text" 
                            ref="title" 
                            name="title" 
                            value={ this.state.title }
                            onChange={ this.handleChange }
                            placeholder="Enter Title" 
                            required />
                        <div className="has-error" style={{color: 'red'}} id="titleError" />      
                        
                    </div>

                    {/*DESCRIPTION*/}
                    {<div className="form-group" >
                        <label id="descriptionLabel" className="control-label">Description</label>
                        <textarea className="form-control" 
                          ref="description" 
                          name="description" 
                          value={ this.state.description }
                          onChange={ this.handleChange }
                          rows="10" 
                          placeholder="Enter Description" 
                          required >
                        </textarea>
                        <div className="has-error" style={{color: 'red'}} id="descriptionError" />           
                    </div>}

                    {/*SUBMIT BUTTON*/}
                    <div className="btn-block text-right">    
                      <input type="submit" className="btn btn-primary" style={{width: 100}} onClick={this.HandleSave} value="Save" />
                      <Link to="/news" className="btn btn-sm btn-danger btn-create" style={{width: 100}} >Cancel</Link>
                    </div>

                 </form>
              }              
            </div>
          </div>
          </div>
      </div>
    );
  }
}
