// client/angular2/NvslOnlineAngular2App/src/app/news/news.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';

import { INews } from '../shared/interfaces/interfaces';
import { News } from '../shared/models/news';

import { DataService } from '../shared/services/data.service';
import { TruncatePipe } from '../shared/pipes/truncate.pipe';

@Component({
  selector: 'app-news',  
  templateUrl: './news.component.html',
  styleUrls: ['./news.component.css']
})
export class NewsComponent implements OnInit {

    news: INews[];
    errorMessage: string;

    constructor(private dataService: DataService,
                private router: Router) {
    }
        
    ngOnInit() {

      this.dataService.getNews()
          .subscribe(
            news => this.news = news,
            error => this.errorMessage = <any>error
          );     
    }

    remove(id: number) {
        if (confirm('Are you sure want to delete this item?')) {
            this.dataService.deleteSingleNews(id)
            .subscribe(
                data => console.log('success: ', data),
                err => console.log('error: ', err),
                () => this.reload()
            );
        }        
    }

    reload(): void {
        this.dataService.getNews()
                .subscribe(news => this.news = news,
                           error => this.errorMessage = <any>error);
        
        this.router.navigate(['/news']);
    }

}

<main class="panel pt-5">
    <div class="card mb-5">
        <div class="card-header">
            <b>News</b>
            <div class="pull-right"><a [routerLink]="['/addnews']" class="btn btn-sm btn-primary btn-create">Create New</a></div>            
        </div>
        <div class="card-block p-0">
            <table class="table table-bordered table-sm m-0">
                <thead class="">
                    <tr>
                        <th></th>
                        <th>Title</th>
                        <th>Description</th>
                        <th>created</th>
                        <!--<th>Created</th>
                        <th>Created By</th>
                        <th>Modified</th>
                        <th>Modified By</th>                        -->
                    </tr>
                </thead>
                <tbody>
                    <tr *ngFor='let singleNews of news'>                        
                        <td>
                            <a class="btn btn-sm btn-primary btn-create" [routerLink]="['/news', singleNews.Id]" >Edit</a>
                            <a class="btn btn-sm btn-danger" (click)='remove(singleNews.Id)' >Delete</a>
                        </td>
                        <td>{{singleNews.title | truncate : 35 }}</td>
                        <td>{{singleNews.description | truncate : 70 }}</td>
                        <td>{{singleNews.created}}</td>
                        <!--<td></td>
                        <td></td>
                        <td></td>
                        <td></td>                 -->
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="card-footer p-0">
        </div>
    </div>
</main>

// client/react/nvslonlineapp/src/components/News/News.js
import React from 'react';
import { Link } from "react-router-dom";
import {Button} from 'react-bootstrap';

import SideBar from '../SideBar.js';
import './News.css';
import api from '../../api/api.js';


export default class News extends React.Component {

  

  constructor()
  {
      super();

      this.handleClick = this.handleClick.bind(this);
      this.reload = this.reload.bind(this);

      this.state = {
        news: []
      }
  } 

  handleClick(e) {
    
      let result = window.confirm('Are you sure want to delete this item?');

      if ( result ) {

          let NewsId = e.target.name;

          api.deleteSinglenNews(NewsId)
            .then((response) => {
                console.log('success');
                this.reload();
                        
            });

      }

  } 

  reload() {

    api.getNews().then((response) => {
          console.log(response);

          this.setState({
			      news: response
		      })
	    });

  }

  componentWillMount() {
      this.reload();
  }

  render() {    

    return (
      <div>        
        <div className="container-fluid">
          <div className="col-md-2 sidebar">
            <SideBar />
          </div>
          <div className="col-md-10">

            <main className="panel pt-5">
              <div className="card mb-5">
                <div className="card-header">
                    <b>News</b>
                    <div className="pull-right">
                      <Link to="/addnews" className="btn btn-sm btn-primary btn-create" >Create New</Link>                      
                    </div>            
                </div>
                <div className="card-block p-0">                  
                  <table className="table table-bordered table-sm m-0">
                    <thead>
                      <tr>
                          <th></th>
                          <th></th>
                          <th>Title</th>
                          <th>Description</th>
                          <th>Date Created</th>                                                                                                  
                      </tr>
                    </thead>
                    <tbody>       
                      {this.state.news.map(function(row, i) {
                        return (
                          <tr key={i}>
                            <td><Link to={"/editnews/" + row.Id} className="btn btn-sm btn-primary btn-create" >Edit</Link></td>
                            {/*<td><Link to="/" className="btn btn-sm btn-danger" >Delete</Link></td>*/}
                            <td><button className="btn btn-sm btn-danger" name={row.Id} onClick={this.handleClick} >Delete</button></td>
                            <td key={row.title}>{row.title}</td>
                            <td key={row.description}>{row.description}</td>
                            <td key={row.created}>{row.created}</td>
                          </tr>
                        );
                      }.bind(this))}                                                           
                    </tbody>
                  </table>
                </div>                
              </div>
            </main>      
                              
          </div>
        </div>
      </div>
    );
  }
}
